FROM python:3.10-slim

WORKDIR /app

COPY requirements_load_generator.txt .
RUN pip install --no-cache-dir -r requirements_load_generator.txt

COPY load_generator.py .

RUN chmod +x load_generator.py

ENTRYPOINT ["python", "load_generator.py"]

