name: Deploy to Azure VM

on:
  push:
    branches:
      - lab5
  pull_request:
    branches:
      - lab5

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd ~/Database_main
            git pull origin lab5
            source .venv/bin/activat
            pip install -r requirements.txt
            sudo systemctl restart moviedb
            curl -f http://localhost:8000/health || exit 1
            echo " Deployment successful!"

